In [1]:
nums = [[3,1,2,4,5],[1,2,3,4],[3,4,5,6]]

In [18]:
set([3,4,5,6]) & set([1,2,3,4])

TypeError: unsupported operand type(s) for &: 'list' and 'list'

In [5]:
sorted(nums, key=lambda x: len(x))

[[1, 2, 3, 4], [3, 4, 5, 6], [3, 1, 2, 4, 5]]

In [6]:
from functools import reduce

In [21]:
comp = nums[0]
for el in nums[1:]:
    temp = []
    for i in comp:
       if i in set(el):
           temp.append(i)
    comp = temp    
print(comp)  
        

[3, 4]


In [98]:
from functools import reduce
class Solution(object):
    def lattice_points_circl(self, x, y, r):
        return {(x,y)} | {(x, y) for x in range(x-r, x + r + 1) if x != y} |{(x, y) for y in range(y-r, y + r + 1) if x != y}
    
    def countLatticePoints(self, circles):
        """
        :type circles: List[List[int]]
        :rtype: int
        """
        return reduce(lambda x, y: x | y, [self.lattice_points_circl(*i) for i in circles])
        

In [102]:
set([tuple([100,100]), tuple([100, 100])])

{(100, 100)}

In [129]:
costs = [[17,2,17],[16,16,5],[14,3,19]]
def two_houses(first, second):
    second = second[1:] + [second.pop(0)]
    print(second)

In [130]:
two_houses([17,2,17],[16,16,5])

[16, 5, 16]


In [124]:
np.where((x_[:,np.newaxis] - x0)**2 + (y_ - y0)**2 <= radius**2)

(array([1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5]),
 array([3, 2, 3, 4, 1, 2, 3, 4, 5, 2, 3, 4, 3]))

In [121]:
(y_ - y0)**2

array([9, 4, 1, 0, 1, 4])